### ISSUE TITLE
Migrating to Qt

### ISSUE THREAD

**Issue by eliluminado** [youtube-dlg/youtube-dl-gui#1]
I would suggest migrating to Qt, it has support for Python 2 and 3, many more widgets and you could implement several features requested on other issues.

**Comment by nodiscc** [comment]
I agree that PyQt would be a better choice, though that would probably mean rewriting youtube-dl-gui from scratch. I have zero experience with Qt, will look into it. Work could probably be started in a `qt-rewrite` branch.

**Comment by eliluminado** [comment]
I have some code to work with Qt and gettext that could serve

**Comment by farseenabdulsalam** [comment]
I have a suggestion. 
I feel that the current UI is a little bit boring.
If we are going to rewrite the UI code, we should redesign it to be something like this.
![FDM UI] 
(http://www.freedownloadmanager.org/public/img/screen_win.png)

**Comment by nodiscc** [comment]
@farseenabdulsalam I've moved your comment to #4, thanks!

**Comment by nodiscc** [comment]
https://github.com/youtube-dlg/youtube-dl-gui/pull/5
