### ISSUE TITLE
Set --no-playlist option by default

### ISSUE THREAD

**Issue by philipzae** [youtube-dlg/youtube-dl-gui#10]
The url of a video when played from within a playlist is like < https://www.youtube.com/watch?v=rYUKf2gWS-4&list=PLAl4aZK3mRv2QTsDOp1CZvDpMAYz9xBpy&index=1 >, but youtube-dl-gui considers this a playlist download and downloads all the entries of the playlist. It should only download a playlist if it is a url like < https://www.youtube.com/playlist?list=PLAl4aZK3mRv2QTsDOp1CZvDpMAYz9xBpy >.

**Comment by nodiscc** [comment]
There is an option `--no-playlist` for this behavior.

**Comment by philipzae** [comment]
If i do `youtube-dl https://www.youtube.com/watch?v=rYUKf2gWS-4&list=PLAl4aZK3mRv2QTsDOp1CZvDpMAYz9xBpy&index=1` at the commandline, it doesnt download the entire playlist, so i'm not sure how `--nop-playlist` is relevant here.

**Comment by nodiscc** [comment]
> at the commandline, it doesnt download the entire playlist

Well for me it does:

```
$ youtube-dl 'https://www.youtube.com/watch?v=rYUKf2gWS-4&list=PLAl4aZK3mRv2QTsDOp1CZvDpMAYz9xBpy&index=1'
[youtube:playlist] Downloading playlist PLAl4aZK3mRv2QTsDOp1CZvDpMAYz9xBpy - add --no-playlist to just download video rYUKf2gWS-4
[youtube:playlist] PLAl4aZK3mRv2QTsDOp1CZvDpMAYz9xBpy: Downloading webpage
[download] Downloading playlist: CNET's Video Vault
[youtube:playlist] playlist CNET's Video Vault: Downloading 9 videos
[download] Downloading video 1 of 9
...
```

**Comment by philipzae** [comment]
yes it seems adding the comma before and after the url does make it download the playlist, wherein `--no-playlist` would be needed. so either ydlg should remove the playlist part of the url before sending it to ydl or `--no-playlist` should be enabled by default.

**Comment by nodiscc** [comment]
> --no-playlist should be enabled by default.

It should definitely be an option in the options dialog. Should it be disabled by default? I think yes because most likely it will try to download playlists when not expected to (like in your usecase). OTOH when the user wants to actually download a playlist, they should manually enable it. I think this should be a very prominent setting (on the main program window?)
