### ISSUE TITLE
Svtplay clips

### ISSUE THREAD

**Issue by serpico1** [youtube-dlg/youtube-dl-gui#2]
I try to download some clips from svtplay but i get error and warning message in YoutubeDLG
http://www.svtplay.se/klipp/9023742/stopptid-om-bjorn-borg
http://www.svtplay.se/klipp/9023448/borgs-dueller-med-mcenroe
http://www.svtplay.se/klipp/1127657/borgs-comeback

**Comment by nodiscc** [comment]
You need to provide more information.

1. Do the clips download successfully despite the warning message?
2. What actual error messages are written to the log `Options -> Log -> View Log`.

**Comment by nodiscc** [comment]
This is a known problem of the youtube-dl backend: please subscribe to https://github.com/rg3/youtube-dl/issues/9809 and wait until this is fixed on their side. When this is solved don't forget to update youtube-dl using the `Update` button.

**Comment by serpico1** [comment]
1. The clips are not downloaded at all
2. log file "WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: http://www.svtplay.se/klipp/9023742/stopptid-om-bjorn-borg"
