### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by serpico1** [youtube-dlg/youtube-dl-gui#7]
I get error message when i try to download from this link the log file says this
WARNING: Falling back on generic information extractor.
ERROR: Unsupported URL: http://www.svtplay.se/klipp/9023742/stopptid-om-bjorn-borg

I have updated Youtube DLG to latest which was released today 23/6

**Comment by nodiscc** [comment]
@serpico1 Youtube-dl's SVT extractor does not support `/klipp/` videos, as you can see here https://github.com/rg3/youtube-dl/blob/e4f90ea0a72711f6577d4cde1dd145f03ab34803/youtube_dl/extractor/svt.py#L107 (only `/video/` URLs). You have to report this problem directly to youtube-dl maintainers [here](https://github.com/rg3/youtube-dl/issues) (please follow the reporting instructions carefully). There is nothing youtube-dlg can do about it.

To access the command line options easily, you have to open a command prompt in the directory where the copy of `youtube-dl.exe` has been downloaded (on Windows this is `C:\Users\me\AppData\Roaming\youtube-dlg` and run `youtube-dl.exe` with the appropriate options.

This is the error I get when trying to download your video:

```
/C/Users/me/AppData/Roaming/youtube-dlg
$ ./youtube-dl.exe --version
2016.06.23.1

/C/Users/me/AppData/Roaming/youtube-dlg
$ ./youtube-dl.exe -v http://www.svtplay.se/klipp/9023742/stopptid-om-bjorn-bor
g
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', 'http://www.svtplay.se/klipp/9023742/stopptid-
om-bjorn-borg']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2016.06.23.1
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[generic] stopptid-om-bjorn-borg: Requesting header
WARNING: Falling back on generic information extractor.
[generic] stopptid-om-bjorn-borg: Downloading webpage
[generic] stopptid-om-bjorn-borg: Extracting information
ERROR: Unsupported URL: http://www.svtplay.se/klipp/9023742/stopptid-om-bjorn-borg
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpylirceiz\build\youtube_dl\YoutubeDL.py", line 676, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpylirceiz\build\youtube_dl\extractor\common.py", line 343, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpylirceiz\build\youtube_dl\extractor\generic.py", line 2140, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: http://www.svtplay.se/klipp/9023742/stopptid-om-bjorn-borg

```

Feel free to ask if you have more questions. I'll try to document troubleshooting sometime soon.
