### ISSUE TITLE
Post processing long/slow

### ISSUE THREAD

**Issue by ghost** [youtube-dlg/youtube-dl-gui#8]
I wonder why the post procesing take a long time and the computer are very slow when the post processing are running. Ith that normal i just wonder. I used the latest Youtube dl.

**Comment by nodiscc** [comment]
Check resource/CPU usage in your system monitor/task manager. Post processing uses ffmpeg for complex media decoding/encoding so it is expected to be resource-intensive, and can take time especially on large files.

Do you have an example URL to test this?

**Comment by serpico1** [comment]
I often download from here. I give a link for you to test.
http://www.oppetarkiv.se/video/9291397/kommissarie-winter-sasong-1-avsnitt-1-av-6
I wonder because earlier when i use Pirateplayer that program dont do anything after the file was downloaded it was ready to use.

**Comment by nodiscc** [comment]
Erf, I get a 403 forbidden (probably country restrictions).

There should be no post-processing if you leave the video format to `default` (which defaults to the best format) and did not check `convert to audio` or `embed subtitles`, otherwise the file will be re-encoded to the format you selected (takes time/CPU).

Can you attach the download log?

**Comment by serpico1** [comment]
The logfile are empty. Maybe its only write when there are error. 

You wrote there should not be any post processing if i leave default and dont embedded subtitle or some like that. I dont choose anything only paste link and download it works really great. But i wonder what the post procesing do i check the activity manage and it looks that ffmpeg use a lot of disc capasity when post processing are going the disc capacity are approx 98 %.

I really like Youtube DLG its a very good program i look forward for the updated i Think you are working on. I have a problem on SVT i make an issue to Youtube dl team and they fix it its really good.

You wrote there are country restrictions but how can the people wich are updated Youtube dl go around country resctrictions?

**Comment by MrS0m30n3** [comment]
You can use a proxy or a VPN to bypass the country restrictions.
Anyway i am closing this on upstream since the nodiscc's answer should cover your question.
